name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          # Переходим в папку с кодом
          cd ESP32S3Marauder-master/esp32s3_marauder/
          # Проверяем, есть ли там platformio.ini
          ls -la
          # Запускаем сборку именно там
          pio run
